version: '3.1'
services:
  db:
    container_name: sql_container
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: equipment_manager
    ports:
      - "3307:3306"
    volumes:
      - $MYSQLPATH
    healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
        timeout: 20s
        retries: 10
  server:
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    image: node_docker
    restart: always
    ports:
      - "3000:3000"
    links:
      - "db:database"


