name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        working-directory: ./server/scripts
        run: sudo sh buildDocker.sh
      - name: start container
        run: sudo sh startup.sh
      - name: Stop all containers
        working-directory: ./server
        run: docker-compose down
