name: Docker Image CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: build Docker image
        working-directory: ./server/scripts
        run: sudo sh buildDocker.sh
      - name: start container
        working-directory: ./server/scripts
        run: sudo sh startupCI.sh
      - name: execute ddl
        run: cd server/scripts && sh executeSQLStatements.sh
      - name: install UI packages
        run: cd digital-equipment-manager-ui && npm install
      - name: install yarn
        run: npm i yarn
      - name: run cy tests
        run: cd digital-equipment-manager-ui && yarn cy:ci
      - name: Stop all containers
        working-directory: ./server
        run: docker-compose down
