name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change dir
        run: cd server/scripts
      - name: Build the Docker image
        run: sudo ./redeploy.sh
      - name: Stop all containers
        run: docker-compose down
