name: Docker Image CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: build Docker image
        working-directory: ./server/scripts
        run: sudo sh buildDocker.sh
      - name: start container
        working-directory: ./server/scripts
        run: sudo sh startupCI.sh
      - name: install frontend
        working-directory: ./digital-equipment-manager-ui
        run: npm install
      - name: Stop all containers
        working-directory: ./server
        run: docker-compose down
